//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataSoporte2020.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class net2020_soporteEntities : DbContext
    {
        public net2020_soporteEntities()
            : base("name=net2020_soporteEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<asignado> asignado { get; set; }
        public virtual DbSet<cliente> cliente { get; set; }
        public virtual DbSet<estado> estado { get; set; }
        public virtual DbSet<operador> operador { get; set; }
        public virtual DbSet<persona> persona { get; set; }
        public virtual DbSet<seguimiento> seguimiento { get; set; }
        public virtual DbSet<solicitud> solicitud { get; set; }
        public virtual DbSet<soporte> soporte { get; set; }
        public virtual DbSet<sucursal> sucursal { get; set; }
        public virtual DbSet<tbl_comuna> tbl_comuna { get; set; }
        public virtual DbSet<tbl_perfil> tbl_perfil { get; set; }
        public virtual DbSet<tbl_provincia> tbl_provincia { get; set; }
        public virtual DbSet<tbl_region> tbl_region { get; set; }
        public virtual DbSet<tbl_usuario> tbl_usuario { get; set; }
        public virtual DbSet<tipoplan> tipoplan { get; set; }
        public virtual DbSet<tiposolicitud> tiposolicitud { get; set; }
    }
}
