//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataSoporte2020.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class solicitud
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public solicitud()
        {
            this.soporte = new HashSet<soporte>();
        }
    
        public long idsolicitud { get; set; }
        public long idcliente { get; set; }
        public Nullable<int> idtiposol { get; set; }
        public System.DateTime fecha { get; set; }
        public string desc_solicitud { get; set; }
        public int idestado { get; set; }
        public Nullable<System.DateTime> fecha_tope { get; set; }
    
        public virtual cliente cliente { get; set; }
        public virtual tiposolicitud tiposolicitud { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<soporte> soporte { get; set; }
    }
}
