//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataSoporte2020.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class soporte
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public soporte()
        {
            this.asignado = new HashSet<asignado>();
        }
    
        public long idsoporte { get; set; }
        public long idsolicitud { get; set; }
        public System.DateTime fecha { get; set; }
        public string desc_soporte { get; set; }
        public int idestado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<asignado> asignado { get; set; }
        public virtual estado estado { get; set; }
        public virtual solicitud solicitud { get; set; }
    }
}
