//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mvcVictoria2020.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class pago
    {
        public int idpago { get; set; }
        public int idreserva { get; set; }
        public int montopago { get; set; }
        public int estado { get; set; }
    
        public virtual reserva reserva { get; set; }
    }
}
