//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mvcVictoria2020.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class reserva
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public reserva()
        {
            this.pago = new HashSet<pago>();
        }
    
        public int idreserva { get; set; }
        public int idhabitacion { get; set; }
        public int idcliente { get; set; }
        public System.DateTime fecha { get; set; }
        public int numdias { get; set; }
        public System.DateTime fechaout { get; set; }
        public int total { get; set; }
        public int estado { get; set; }
    
        public virtual cliente cliente { get; set; }
        public virtual habitacion habitacion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pago> pago { get; set; }
    }
}
